spring.application.name=ProyectoGrado

spring.config.import=file:secret.properties

spring.jpa.database=${DATABASE}

spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USER}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=${DATASOURCE_DRIVER}

spring.jpa.hibernate.ddl-auto=${JPA_HIBERNATE_DDL}
spring.jpa.show-sql=${JPA_HIBERNATE_SHOW}

gemini.api.key=${API_KEY}
gemini.api.url=${API_URL}

jdoodle.client.id=${JDOODLE_CLIENT_ID}
jdoodle.client.secret=${JDOODLE_CLIENT_SECRET}
jdoodle.api.url=${JDOODLE_API_URL}
